name: mvvm
description: A new Flutter project.


publish_to: 'none'

version: 10.0.0+10

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  flutter_treeview:
  syncfusion_flutter_gauges:
  http: ^0.13.4
  another_flushbar: ^1.10.29
  provider: ^6.0.3
  shared_preferences:
  connectivity:
  fl_chart:
  google_fonts:
  intl:
  flutter_tree:
  google_maps_flutter: ^2.2.0
  package_info:
  pie_chart: ^5.3.2
  sqflite:
  charts_flutter:
  url_launcher:
  flutter_launcher_icons:
  version:
  path_provider:
  geolocator:
  jiffy:
  share:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color: "#ffffff"
  adaptive_icon_background: "#ffffff"
  image_path: "assets/ico2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/person.jpg
    - assets/500-fingerprint-security-outline.gif
    - assets/vs.png
    - assets/vs2.png
    - assets/icon.png
    - assets/ic_launcher_round.png
    - assets/PREMIER.gif
    - assets/pills-solid.png
    - assets/pharma.png
    - assets/all.png
    - assets/pills-solid.png
    - assets/fmcg.png
    - assets/f-solid.png
    - assets/a-solid.png
    - assets/person-military-pointing-solid.png
    - assets/cart-shopping-solid.png
    - assets/a.jpg
    - assets/p-solid.png
    - assets/c-solid.png
    - assets/total_sales.png
    - assets/whatsapp.png
    - assets/pulsenewiconwhite.png
    - assets/pulsenewicon.png
    - assets/icon.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#     - family: MeriendaBold
#       fonts:
#          - asset: fonts/Merienda-Bold.ttf
     - family: MeriendaRegular
       fonts:
          - asset: fonts/Merienda-Regular.ttf
     - family: Lalezar-Regular
       fonts:
          - asset: assets/fonts/Lalezar-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
